version: "2"

volumes:
  db-data:
    driver:
      local

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      rails s -b 0.0.0.0 -p 3000
      # volumes:
        # - $PWD:/usr/src/app
    links:
      - db
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - 5432:5432
  phppgadmin:
    image: turgon37/phppgadmin
    links:
      - db
    ports:
      - 8080:80
    environment:
      - POSTGRES_HOST=db
      - PHPPGADMIN_LOGIN_SECURITY=0